---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(stringr)
```

Load the data files
```{r message=FALSE, warning=FALSE}
data.all <- NA
data.files <- dir('data')
for(f in data.files){
  method <- str_split(f, "_")[[1]][1]
  duration <- as.numeric(str_sub(str_split(f,"_")[[1]][2],start=1,end=-5))
  data.this <- read_tsv(paste0('data/', f)) %>% 
    select(c('Opto 3 Onset', 'Opto 3 Offset')) %>%
    mutate(method=method, duration=duration) %>%
    slice(2:101)
  if(is.na(data.all)){
    data.all <- data.this
  } else {
    data.all <- rbind(data.all, data.this)
  }
}
```

Calculate measured duration, frame durations
```{r}
frame.rate <- 1000/60
data.all <- data.all %>% 
  mutate(obs.duration = `Opto 3 Offset` - `Opto 3 Onset`) %>% 
  mutate(frames = round(obs.duration / frame.rate), desired.frames = round(duration / frame.rate))
```

Calculate errors
```{r}
data.all <- data.all %>%
  mutate(frame.error = frames - desired.frames)

error.summary <- data.all %>% group_by(method, desired.frames, frame.error) %>% summarize(count = n())

error.summary
```

```{r}
ggplot(error.summary, aes(x=frame.error, y=count, fill=method))+
  scale_fill_brewer(type="qual", palette = "Set1", name="Method")+
  geom_vline(xintercept = 0, color="grey50")+
  geom_bar(stat='identity') +
  labs(x="Error in displayed frame count", y="Count")+
  facet_grid(method ~ desired.frames)+
  theme_minimal()+
  theme(panel.grid=element_blank())
```
